PersonalTimeSheet/Models/PagingInfo.cs
using System;

namespace PersonalTimeSheet.Models
{
    public class PagingInfo
    {
        public int TotalItems { get; set; }
        public int ItemsPerPage { get; set; }
        public int CurrentPage { get; set; }

        public int TotalPages
        {
            get { return (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage); }
        }
    }
}

PersonalTimeSheet/Models/RowListViewModel.cs
using System.Collections.Generic;
using PersonalTimeSheet.DBUtils;

namespace PersonalTimeSheet.Models
{
    public class RowListViewModel
    {
        public List<Row> Rows;
        public PagingInfo Info;
    }
}

PersonalTimeSheet/Controllers/RowController.cs
using System;
using System.Web.Mvc;
using PersonalTimeSheet.DBUtils;
using PersonalTimeSheet.Models;
using System.Linq;

namespace PersonalTimeSheet.Controllers
{
    public class RowController : Controller
    {
        private DbService _dbService = new DbService();

        public int PageSize = 6;

        public ViewResult List(int page = 1)
        {
            var viewModel = new RowListViewModel()
                {
                    Rows = _dbService.Rows
                                     .OrderBy(i => i.Id)
                                     .Skip((page - 1)*PageSize)
                                     .Take(PageSize).ToList(),

                    Info = new PagingInfo()
                        {
                            CurrentPage = page,
                            ItemsPerPage = PageSize,
                            TotalItems = _dbService.Rows.Count
                        }
                };

            Session["curPage"] = page;

            return View(viewModel);
        }

        public ViewResult EditRow(int rowId=1)
        {
            var row = _dbService.Rows.SingleOrDefault(r => r.Id == rowId);
            if (null != row)
            {
                return View("EditRow2", row);
            }

            return View("EditRow2", new Row());
        }

        [HttpPost]
        public RedirectToRouteResult EditRow(Row row)
        {
            if (ModelState.IsValid)
            {
                _dbService.UpdateTableRow(row);
                return RedirectToAction("List", new { page = Convert.ToInt16(Session["curPage"]) });
            }

            return RedirectToAction("EditRow", new { rowId = row.Id });
        }

        public RedirectToRouteResult RemoveRow(int rowId, string returnUrl)
        {
            _dbService.RemoveTableRow(rowId);

            return RedirectToAction("List", new {page = Convert.ToInt16(Session["curPage"])});
        }

        public ViewResult NewRow()
        {
            return View(new Row());
        }

        [HttpPost]
        public RedirectToRouteResult NewRow(Row row)
        {
            if (ModelState.IsValid)
            {
                _dbService.AddTableRow(row);
                return RedirectToAction("List", new { page = Convert.ToInt16(Session["curPage"]) });
            }

            return RedirectToAction("NewRow");
        }

    }
}

PersonalTimeSheet/Views/Row/EditRow2.cshtml
@model PersonalTimeSheet.DBUtils.Row

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

        @using (Html.BeginForm())
        {
            @Html.ValidationSummary(true);
            <h3>Update Task</h3>
            <div style="display: none">@Html.EditorFor(x=>x.Id)</div>
            <div>Title : @Html.EditorFor(x => x.Title)</div>
            <br/>
            <div>Description : @Html.EditorFor(x => x.Description)</div>
            <br/>
            <div>Spent Time : @Html.EditorFor(x => x.SpentTime)</div>

            <p align="left">
                <input class="actionButtons" type="submit" value="Upadate" />
            </p>
        }

        @using (Html.BeginForm("List", "Row"))
        {
            @Html.Hidden("page", Session["curPage"])
            <input class="actionButtons" type="submit" value="Back" />
        }

PersonalTimeSheet/Views/Row/List.cshtml
@using PersonalTimeSheet.HtmlHelper
@model PersonalTimeSheet.Models.RowListViewModel

@{
    ViewBag.Title = "List";
}

<table>
    <tr id="tableHeader">
       <td>
            Title
        </td>
        <td>
            Description
        </td>
       <td>
            Time Spent
        </td>
    </tr>
    @foreach (var p in Model.Rows)
    {
        Html.RenderPartial("RowSummary", p); 
    }
</table>

<div class="pager">
    @Html.PageLinks(Model.Info, x => Url.Action("List", new {page = x}))
</div>

<div style="display: inline-block;">
    @using (Html.BeginForm("NewRow", "Row"))
    {          
        <input class="actionButtons" type="submit" value="Add New Task" />
    }
</div>

PersonalTimeSheet/Views/Row/NewRow.cshtml
@model PersonalTimeSheet.DBUtils.Row

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <h3>Create New Task</h3>
    <div>Title : @Html.EditorFor(x => x.Title)</div>
    <br/>
    <div>Description : @Html.EditorFor(x => x.Description)</div>
    <br/>
    <div>Spent Time : @Html.EditorFor(x => x.SpentTime)</div>

    <p align="left">
        <input class="actionButtons" type="submit" value="Save" />
    </p>
}

 @using (Html.BeginForm("List", "Row"))
{
    @Html.Hidden("page", Session["curPage"])
    <input class="actionButtons" type="submit" value="Back" />
}

PersonalTimeSheet/Views/Shared/RowSummary.cshtml
@model PersonalTimeSheet.DBUtils.Row
           
<tr class="item">
    <td>
        @Model.Title
    </td>
    <td>
        @Model.Description
    </td>
    <td>
        @Model.SpentTime.ToString()
    </td>
    <td style="border: none; width: 15%;">
        <div style="display: inline;">
            
            @using (Html.BeginForm("EditRow", "Row"))
            {
                @Html.Hidden("rowId", Model.Id)
               <input class="actionButtons" type="submit" value="Edit" />
            }

            @using (Html.BeginForm("RemoveRow", "Row"))
            {
                @Html.Hidden("rowId", Model.Id)
                @Html.Hidden("returnUrl", "/?page=" + Session["curPage"].ToString())
                <input class="actionButtons" type="submit" value="Remove" />
            }
        </div>
    </td>
</tr>

PersonalTimeSheet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-2.5.3.js")" type="text/javascript"></script>
    <link href="@Url.Content("~/Scripts/Facebox/facebox.css")" media="screen" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/Facebox/facebox.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/Facebox/FaceboxScript.js")" type="text/javascript"></script>

</head>

    <body>
        <div id="header">
            <div class="title">Personal Time Sheet</div>
        </div>
        <div id="menu">
        </div>
        <div id="content">
            @RenderBody()
        </div>
        
        </body>
</html>